name: Format Code with pre commit trigger
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - name: setup
        run: |
          sudo apt update 
          sudo apt install -y clang clang-format
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v32
      - name: Check format of cpp changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ "${file##*.}" =~ ^(h|o|i|C|cc|cp|cpp|c++|CPP|cxx)$ ]]; then
              clang-format --dry-run --Werror $file
            fi
          done
  readability:
    runs-on: ubuntu-22.04
    steps:
      - name: setup
        run: |
          sudo apt update 
          sudo apt install -y clang clang-tidy
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v32
      - name: Check readability of cpp changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ "${file##*.}" =~ ^(h|o|i|C|cc|cp|cpp|c++|CPP|cxx)$ ]]; then
              clang-tidy $file
            fi
          done
        
