name: Post clang-tidy review comments

on:
  workflow_dispatch:
  workflow_run:
    # The name field of the lint action .github/workflows/github-actions-clang-tidy.yml
    workflows: ["clang-tidy-review"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: The-OpenROAD-Project/clang-tidy-review/post@test-pyyaml
